import typing

CLOCK_DATA_STORE: typing.Final[str] = "clock.data.store"
DICTIONARY: typing.Final[str] = "dictionary"
LPU: typing.Final[str] = "lpu"
PDF_CONTRAST: typing.Final[str] = "pdf.contrast"
SYNC_LPR: typing.Final[str] = "sync_lpr"
TPZ_LINE_SPACING: typing.Final[str] = "tpz.line.spacing"
XRAY_OTA_UPDATE_STATE: typing.Final[str] = "XRAY_OTA_UPDATE_STATE"
XRAY_SHOWING_SPOILERS: typing.Final[str] = "XRAY_SHOWING_SPOILERS"
XRAY_SORTING_STATE: typing.Final[str] = "XRAY_SORTING_STATE"
XRAY_TAB_STATE: typing.Final[str] = "XRAY_TAB_STATE"
DICT_PREFS_V_2: typing.Final[str] = "dict.prefs.v2"
END_ACTIONS: typing.Final[str] = "EndActions"
READER_METRICS: typing.Final[str] = "ReaderMetrics"
START_ACTIONS: typing.Final[str] = "StartActions"
TRANSLATOR: typing.Final[str] = "Translator"
WIKIPEDIA: typing.Final[str] = "Wikipedia"
BUY_ASIN_RESPONSE_DATA: typing.Final[str] = "buy.asin.response.data"
NEXT_IN_SERIES_INFO_DATA: typing.Final[str] = "next.in.series.info.data"
PRICE_INFO_DATA: typing.Final[str] = "price.info.data"
ERL: typing.Final[str] = "erl"
LPR: typing.Final[str] = "lpr"
FPR: typing.Final[str] = "fpr"
UPDATED_LPR: typing.Final[str] = "updated_lpr"
APNX_KEY: typing.Final[str] = "apnx.key"
FIXED_LAYOUT_DATA: typing.Final[str] = "fixed.layout.data"
SHARING_LIMITS: typing.Final[str] = "sharing.limits"
LANGUAGE_STORE: typing.Final[str] = "language.store"
PERIODICALS_VIEW_STATE: typing.Final[str] = "periodicals.view.state"
PURCHASE_STATE_DATA: typing.Final[str] = "purchase.state.data"
TIMER_DATA_STORE: typing.Final[str] = "timer.data.store"
TIMER_DATA_STORE_V2: typing.Final[str] = "timer.data.store.v2"
BOOK_INFO_STORE: typing.Final[str] = "book.info.store"
PAGE_HISTORY_STORE: typing.Final[str] = "page.history.store"
READER_STATE_PREFERENCES: typing.Final[str] = "reader.state.preferences"
FONT_PREFS: typing.Final[str] = "font.prefs"
SAVED_AVL_INTERVAL_TREE: typing.Final[str] = "saved.avl.interval.tree"
ANNOTATION_CACHE_OBJECT: typing.Final[str] = "annotation.cache.object"
ANNOTATION_PERSONAL_BOOKMARK: typing.Final[str] = "annotation.personal.bookmark"
ANNOTATION_PERSONAL_HIGHLIGHT: typing.Final[str
                                            ] = "annotation.personal.highlight"
ANNOTATION_PERSONAL_NOTE: typing.Final[str] = "annotation.personal.note"
ANNOTATION_PERSONAL_CLIP_ARTICLE: typing.Final[
    str] = "annotation.personal.clip_article"
